config.load_autoconfig(False)
config.set("colors.completion.category.bg", "#282c34")
config.set("colors.completion.category.border.bottom", "#282c34")
config.set("colors.completion.category.border.top", "#282c34")
config.set("colors.completion.category.fg", "#98c379")
config.set("colors.completion.even.bg", "#282c34")
config.set("colors.completion.fg", "#abb2bf")
config.set("colors.completion.item.selected.bg", "#545862")
config.set("colors.completion.item.selected.border.bottom", "#545862")
config.set("colors.completion.item.selected.border.top", "#545862")
config.set("colors.completion.item.selected.fg", "#abb2bf")
config.set("colors.completion.item.selected.match.fg", "#98c379")
config.set("colors.completion.match.fg", "#98c379")
config.set("colors.completion.odd.bg", "#353b45")
config.set("colors.completion.scrollbar.bg", "#282c34")
config.set("colors.completion.scrollbar.fg", "#abb2bf")
config.set("colors.contextmenu.disabled.bg", "#353b45")
config.set("colors.contextmenu.disabled.fg", "#282c34")
config.set("colors.contextmenu.menu.bg", "#282c34")
config.set("colors.contextmenu.menu.fg", "#abb2bf")
config.set("colors.contextmenu.selected.bg", "#545862")
config.set("colors.contextmenu.selected.fg", "#abb2bf")
config.set("colors.downloads.bar.bg", "#282c34")
config.set("colors.downloads.error.bg", "#e06c75")
config.set("colors.downloads.error.fg", "#282c34")
config.set("colors.downloads.start.bg", "#98c379")
config.set("colors.downloads.start.fg", "#282c34")
config.set("colors.downloads.stop.bg", "#56b6c2")
config.set("colors.downloads.stop.fg", "#282c34")
config.set("colors.hints.bg", "#353b45")
config.set("colors.hints.fg", "#abb2bf")
config.set("colors.hints.match.fg", "#98c379")
config.set("colors.keyhint.bg", "#282c34")
config.set("colors.keyhint.fg", "#abb2bf")
config.set("colors.keyhint.suffix.fg", "#abb2bf")
config.set("colors.messages.error.bg", "#e06c75")
config.set("colors.messages.error.border", "#e06c75")
config.set("colors.messages.error.fg", "#282c34")
config.set("colors.messages.info.bg", "#98c379")
config.set("colors.messages.info.border", "#98c379")
config.set("colors.messages.info.fg", "#282c34")
config.set("colors.messages.warning.bg", "#c678dd")
config.set("colors.messages.warning.border", "#c678dd")
config.set("colors.messages.warning.fg", "#282c34")
config.set("colors.prompts.bg", "#282c34")
config.set("colors.prompts.border", "1px solid #282c34")
config.set("colors.prompts.fg", "#abb2bf")
config.set("colors.prompts.selected.bg", "#353b45")
config.set("colors.prompts.selected.fg", "#abb2bf")
config.set("colors.statusbar.caret.bg", "#545862")
config.set("colors.statusbar.caret.fg", "#abb2bf")
config.set("colors.statusbar.caret.selection.bg", "#545862")
config.set("colors.statusbar.caret.selection.fg", "#abb2bf")
config.set("colors.statusbar.command.bg", "#282c34")
config.set("colors.statusbar.command.fg", "#abb2bf")
config.set("colors.statusbar.command.private.bg", "#353b45")
config.set("colors.statusbar.command.private.fg", "#abb2bf")
config.set("colors.statusbar.insert.bg", "#98c379")
config.set("colors.statusbar.insert.fg", "#282c34")
config.set("colors.statusbar.normal.bg", "#282c34")
config.set("colors.statusbar.normal.fg", "#abb2bf")
config.set("colors.statusbar.passthrough.bg", "#56b6c2")
config.set("colors.statusbar.passthrough.fg", "#282c34")
config.set("colors.statusbar.private.bg", "#353b45")
config.set("colors.statusbar.private.fg", "#abb2bf")
config.set("colors.statusbar.progress.bg", "#98c379")
config.set("colors.statusbar.url.error.fg", "#e06c75")
config.set("colors.statusbar.url.fg", "#abb2bf")
config.set("colors.statusbar.url.hover.fg", "#abb2bf")
config.set("colors.statusbar.url.success.http.fg", "#56b6c2")
config.set("colors.statusbar.url.success.https.fg", "#98c379")
config.set("colors.statusbar.url.warn.fg", "#c678dd")
config.set("colors.tabs.bar.bg", "#282c34")
config.set("colors.tabs.even.bg", "#353b45")
config.set("colors.tabs.even.fg", "#abb2bf")
config.set("colors.tabs.indicator.error", "#e06c75")
config.set("colors.tabs.indicator.start", "#56b6c2")
config.set("colors.tabs.indicator.stop", "#98c379")
config.set("colors.tabs.odd.bg", "#282c34")
config.set("colors.tabs.odd.fg", "#abb2bf")
config.set("colors.tabs.pinned.even.bg", "#98c379")
config.set("colors.tabs.pinned.even.fg", "#282c34")
config.set("colors.tabs.pinned.odd.bg", "#56b6c2")
config.set("colors.tabs.pinned.odd.fg", "#282c34")
config.set("colors.tabs.pinned.selected.even.bg", "#545862")
config.set("colors.tabs.pinned.selected.even.fg", "#abb2bf")
config.set("colors.tabs.pinned.selected.odd.bg", "#545862")
config.set("colors.tabs.pinned.selected.odd.fg", "#abb2bf")
config.set("colors.tabs.selected.even.bg", "#545862")
config.set("colors.tabs.selected.even.fg", "#abb2bf")
config.set("colors.tabs.selected.odd.bg", "#545862")
config.set("colors.tabs.selected.odd.fg", "#abb2bf")
config.set("colors.tooltip.bg", "#282c34")
config.set("colors.tooltip.fg", "#abb2bf")
config.set("colors.webpage.preferred_color_scheme", "dark")
config.set("completion.height", "30%")
config.set("content.blocking.whitelist", [])
config.set("content.javascript.modal_dialog", True)
config.set("editor.command", ["emacsclient", "-c", "--alternate-editor=", "{}"])
config.set("fonts.default_family", "JetBrainsMono Nerd Font")
config.set("fonts.default_size", "12pt")
config.set("fonts.web.family.cursive", "JetBrainsMono Nerd Font")
config.set("fonts.web.family.fantasy", "JetBrainsMono Nerd Font")
config.set("fonts.web.family.fixed", "JetBrainsMono Nerd Font")
config.set("fonts.web.family.sans_serif", "JetBrainsMono Nerd Font")
config.set("fonts.web.family.serif", "JetBrainsMono Nerd Font")
config.set("fonts.web.family.standard", "JetBrainsMono Nerd Font")
config.set("fonts.web.size.default", 16)
config.set("hints.border", "1px solid #282c34")
config.set("input.forward_unbound_keys", "all")
config.set("input.insert_mode.auto_enter", False)
config.set("input.insert_mode.auto_leave", False)
config.set("input.insert_mode.plugins", False)
c.url.searchengines['aw'] = "https://wiki.archlinux.org/?search={}"
c.url.searchengines['g'] = "https://www.google.com/search?hl=en&q={}"
c.url.searchengines['no'] = "https://search.nixos.org/options?channel=unstable&query={}"
c.url.searchengines['np'] = "https://search.nixos.org/packages?channel=unstable&query={}"
c.url.searchengines['nw'] = "https://wiki.nixos.org/index.php?search={}"
c.url.searchengines['w'] = "https://en.wikipedia.org/wiki/Special:Search?search={}&go=Go&ns0=1"
c.url.searchengines['yt'] = "https://www.youtube.com/results?search_query={}"
c.url.searchengines['ytm'] = "https://music.youtube.com/results?search_query={}"
config.bind("<ctrl-g>", "mode-leave", mode="caret")
config.bind("<alt-n>", "command-history-next", mode="command")
config.bind("<alt-p>", "command-history-prev", mode="command")
config.bind("<ctrl-g>", "mode-leave", mode="command")
config.bind("<ctrl-m>", "command-accept", mode="command")
config.bind("<ctrl-n>", "completion-item-focus next", mode="command")
config.bind("<ctrl-p>", "completion-item-focus prev", mode="command")
config.bind("<ctrl-r>", "search-prev", mode="command")
config.bind("<ctrl-s>", "search-next", mode="command")
config.bind("<escape>", "mode-leave", mode="command")
config.bind("<return>", "command-accept", mode="command")
config.bind("<ctrl-g>", "mode-leave", mode="hint")
config.bind("<ctrl-m>", "follow-hint", mode="hint")
config.bind("<escape>", "mode-leave", mode="hint")
config.bind("<return>", "follow-hint", mode="hint")
config.bind("<ctrl-e>", "open-editor", mode="insert")
config.bind("<ctrl-g>", "mode-leave", mode="insert")
config.bind("<escape>", "mode-leave", mode="insert")
config.bind("0", "fake-key 0", mode="normal")
config.bind("1", "fake-key 1", mode="normal")
config.bind("2", "fake-key 2", mode="normal")
config.bind("3", "fake-key 3", mode="normal")
config.bind("4", "fake-key 4", mode="normal")
config.bind("5", "fake-key 5", mode="normal")
config.bind("6", "fake-key 6", mode="normal")
config.bind("7", "fake-key 7", mode="normal")
config.bind("8", "fake-key 8", mode="normal")
config.bind("9", "fake-key 9", mode="normal")
config.bind("<Ctrl+/>V", "hint links spawn --detach mpv {hint-url}", mode="normal")
config.bind("<Ctrl+/>v", "spawn --detach mpv {url}", mode="normal")
config.bind("<alt-a>", "tab-prev", mode="normal")
config.bind("<alt-b>", "fake-key <Ctrl-Left>", mode="normal")
config.bind("<alt-backspace>", "fake-key <Ctrl-Backspace>", mode="normal")
config.bind("<alt-d>", "fake-key <Ctrl-Delete>", mode="normal")
config.bind("<alt-e>", "tab-next", mode="normal")
config.bind("<alt-f>", "fake-key <Ctrl-Right>", mode="normal")
config.bind("<alt-l>", "cmd-set-text -s :open -t", mode="normal")
config.bind("<alt-shift-,>", "scroll-to-perc 0", mode="normal")
config.bind("<alt-shift-.>", "scroll-to-perc", mode="normal")
config.bind("<alt-shift-v>", "scroll-page 0 -1", mode="normal")
config.bind("<alt-v>", "scroll-page 0 -0.5", mode="normal")
config.bind("<alt-w>", "yank", mode="normal")
config.bind("<alt-x>", "cmd-set-text :", mode="normal")
config.bind("<ctrl-[>", "back", mode="normal")
config.bind("<ctrl-]>", "forward", mode="normal")
config.bind("<ctrl-a>", "fake-key <Home>", mode="normal")
config.bind("<ctrl-b>", "fake-key <Left>", mode="normal")
config.bind("<ctrl-d>", "fake-key <Delete>", mode="normal")
config.bind("<ctrl-e>", "fake-key <End>", mode="normal")
config.bind("<ctrl-f>", "fake-key <Right>", mode="normal")
config.bind("<ctrl-g>", "clear-keychain ;; search ;; fullscreen --leave", mode="normal")
config.bind("<ctrl-h>", "cmd-set-text -s :help", mode="normal")
config.bind("<ctrl-l>", "cmd-set-text -s :open", mode="normal")
config.bind("<ctrl-m>", "mode-enter insert", mode="normal")
config.bind("<ctrl-n>", "fake-key <Down>", mode="normal")
config.bind("<ctrl-p>", "fake-key <Up>", mode="normal")
config.bind("<ctrl-r>", "cmd-set-text ?", mode="normal")
config.bind("<ctrl-s>", "cmd-set-text /", mode="normal")
config.bind("<ctrl-shift-tab>", "tab-prev", mode="normal")
config.bind("<ctrl-shift-v>", "scroll-page 0 1", mode="normal")
config.bind("<ctrl-space>", "hint all", mode="normal")
config.bind("<ctrl-tab>", "tab-next", mode="normal")
config.bind("<ctrl-u><alt-w>d", "yank domain", mode="normal")
config.bind("<ctrl-u><alt-w>p", "yank pretty-url", mode="normal")
config.bind("<ctrl-u><alt-w>t", "yank title", mode="normal")
config.bind("<ctrl-u><ctrl-space>", "hint --rapid links tab-bg", mode="normal")
config.bind("<ctrl-u><ctrl-x><ctrl-f>", "cmd-set-text -s :open", mode="normal")
config.bind("<ctrl-v>", "scroll-page 0 0.5", mode="normal")
config.bind("<ctrl-w>", "fake-key <Ctrl-backspace>", mode="normal")
config.bind("<ctrl-x>0", "tab-close", mode="normal")
config.bind("<ctrl-x>1", "tab-only", mode="normal")
config.bind("<ctrl-x><ctrl-c>", "quit", mode="normal")
config.bind("<ctrl-x><ctrl-f>", "cmd-set-text -s :open -t", mode="normal")
config.bind("<ctrl-x>b", "cmd-set-text -s :buffer", mode="normal")
config.bind("<ctrl-x>k", "tab-close", mode="normal")
config.bind("<ctrl-x>l", "reload", mode="normal")
config.bind("<ctrl-x>xg", "config-source", mode="normal")
config.bind("<ctrl-y>", "insert-text {primary}", mode="normal")
config.bind("<ctrl-g>", "mode-leave", mode="prompt")
config.bind("<ctrl-m>", "prompt-accept", mode="prompt")
config.bind("<ctrl-n>", "prompt-item-focus next", mode="prompt")
config.bind("<ctrl-p>", "prompt-item-focus prev", mode="prompt")
config.bind("<escape>", "mode-leave", mode="prompt")
config.bind("<return>", "prompt-accept", mode="prompt")
config.bind("n", "prompt-accept no", mode="prompt")
config.bind("y", "prompt-accept yes", mode="prompt")
c.bindings.default['normal'] = {}
