-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/

-- settings.locals
local mod = 'SUPER'

-- settings.curve
hl.curve('easeInOutCubic', {
  points = {
    { 0.65, 0.05 },
    { 0.36, 1 },
  },
  type = 'bezier',
})
hl.curve('easeOutQuint', {
  ['points'] = {
    { 0.23, 1 },
    { 0.32, 1 },
  },
  ['type'] = 'bezier',
})
hl.curve('linear', {
  ['points'] = {
    { 0, 0 },
    { 1, 1 },
  },
  ['type'] = 'bezier',
})
hl.curve('almostLinear', {
  ['points'] = {
    { 0.5, 0.5 },
    { 0.75, 1 },
  },
  ['type'] = 'bezier',
})
hl.curve('quick', {
  ['points'] = {
    { 0.15, 0 },
    { 0.1, 1 },
  },
  ['type'] = 'bezier',
})
hl.curve('easy', {
  ['dampening'] = 15.8273644,
  ['mass'] = 1,
  ['stiffness'] = 71.2633,
  ['type'] = 'spring',
})

-- settings.animation
hl.animation({
  ['bezier'] = 'default',
  ['enabled'] = true,
  ['leaf'] = 'global',
  ['speed'] = 10,
})
hl.animation({
  ['bezier'] = 'easeOutQuint',
  ['enabled'] = true,
  ['leaf'] = 'border',
  ['speed'] = 5.39,
})
hl.animation({
  ['enabled'] = true,
  ['leaf'] = 'windows',
  ['speed'] = 4.79,
  ['spring'] = 'easy',
})
hl.animation({
  ['enabled'] = true,
  ['leaf'] = 'windowsIn',
  ['speed'] = 4.1,
  ['spring'] = 'easy',
  ['style'] = 'popin 87%',
})
hl.animation({
  ['bezier'] = 'linear',
  ['enabled'] = true,
  ['leaf'] = 'windowsOut',
  ['speed'] = 1.49,
  ['style'] = 'popin 87%',
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'fadeIn',
  ['speed'] = 1.73,
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'fadeOut',
  ['speed'] = 1.46,
})
hl.animation({
  ['bezier'] = 'quick',
  ['enabled'] = true,
  ['leaf'] = 'fade',
  ['speed'] = 3.03,
})
hl.animation({
  ['bezier'] = 'easeOutQuint',
  ['enabled'] = true,
  ['leaf'] = 'layers',
  ['speed'] = 3.81,
})
hl.animation({
  ['bezier'] = 'easeOutQuint',
  ['enabled'] = true,
  ['leaf'] = 'layersIn',
  ['speed'] = 4,
  ['style'] = 'fade',
})
hl.animation({
  ['bezier'] = 'linear',
  ['enabled'] = true,
  ['leaf'] = 'layersOut',
  ['speed'] = 1.5,
  ['style'] = 'fade',
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'fadeLayersIn',
  ['speed'] = 1.79,
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'fadeLayersOut',
  ['speed'] = 1.39,
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'workspaces',
  ['speed'] = 1.94,
  ['style'] = 'fade',
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'workspacesIn',
  ['speed'] = 1.21,
  ['style'] = 'fade',
})
hl.animation({
  ['bezier'] = 'almostLinear',
  ['enabled'] = true,
  ['leaf'] = 'workspacesOut',
  ['speed'] = 1.94,
  ['style'] = 'fade',
})
hl.animation({
  ['bezier'] = 'quick',
  ['enabled'] = true,
  ['leaf'] = 'zoomFactor',
  ['speed'] = 7,
})

-- settings.bind (native, DMS has no equivalent)
hl.bind((mod .. ' + Q'), (hl.dsp.window.close()), { ['locked'] = true })
hl.bind(
  (mod .. ' + SHIFT + F'),
  (hl.dsp.window.fullscreen({ mode = 'fullscreen', action = 'toggle' }))
)
hl.bind(
  (mod .. ' + F'),
  (hl.dsp.window.fullscreen({ mode = 'maximized', action = 'toggle' }))
)
hl.bind((mod .. ' + RETURN'), (hl.dsp.exec_cmd('runapp xdg-terminal-exec')))
hl.bind((mod .. ' + E'), (hl.dsp.exec_cmd('dolphin')))
hl.bind((mod .. ' + V'), (hl.dsp.window.float({ action = 'toggle' }))) -- kept: DMS has no float-toggle equivalent
hl.bind((mod .. ' + P'), (hl.dsp.window.pseudo()))
hl.bind(
  (mod .. ' + SHIFT + M'),
  (
    hl.dsp.exec_cmd(
      "command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"
    )
  )
) -- moved off mod+M, see DMS processlist below
hl.bind((mod .. ' + l'), (hl.dsp.focus({ direction = 'right' })))
hl.bind((mod .. ' + h'), (hl.dsp.focus({ direction = 'left' })))
hl.bind((mod .. ' + k'), (hl.dsp.focus({ direction = 'up' })))
hl.bind((mod .. ' + j'), (hl.dsp.focus({ direction = 'down' })))
hl.bind((mod .. ' + SHIFT + l'), (hl.dsp.window.move({ direction = 'right' })))
hl.bind((mod .. ' + SHIFT + h'), (hl.dsp.window.move({ direction = 'left' })))
hl.bind((mod .. ' + SHIFT + k'), (hl.dsp.window.move({ direction = 'up' })))
hl.bind((mod .. ' + SHIFT + j'), (hl.dsp.window.move({ direction = 'down' })))
hl.bind((mod .. ' + S'), (hl.dsp.workspace.toggle_special('magic')))
hl.bind(
  (mod .. ' + SHIFT + S'),
  (hl.dsp.window.move({ workspace = 'special:magic' }))
)
hl.bind((mod .. ' + mouse_down'), (hl.dsp.focus({ workspace = 'e+1' })))
hl.bind((mod .. ' + mouse_up'), (hl.dsp.focus({ workspace = 'e-1' })))
hl.bind((mod .. ' + bracketleft'), (hl.dsp.focus({ workspace = 'e-1' })))
hl.bind((mod .. ' + bracketright'), (hl.dsp.focus({ workspace = 'e+1' })))
hl.bind((mod .. ' + mouse:272'), (hl.dsp.window.drag()), { ['mouse'] = true })
hl.bind((mod .. ' + mouse:273'), (hl.dsp.window.resize()), { ['mouse'] = true })

-- kept: no DMS equivalent for mic mute or media transport keys
hl.bind(
  'XF86AudioMicMute',
  (hl.dsp.exec_cmd('wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle')),
  { ['locked'] = true, ['repeating'] = true }
)
hl.bind('XF86AudioNext', (hl.dsp.exec_cmd('playerctl next')), { ['locked'] = true })
hl.bind(
  'XF86AudioPause',
  (hl.dsp.exec_cmd('playerctl play-pause')),
  { ['locked'] = true }
)
hl.bind(
  'XF86AudioPlay',
  (hl.dsp.exec_cmd('playerctl play-pause')),
  { ['locked'] = true }
)
hl.bind(
  'XF86AudioPrev',
  (hl.dsp.exec_cmd('playerctl previous')),
  { ['locked'] = true }
)

-- settings.config
hl.config({
  ['animations'] = { ['enabled'] = true },
  ['binds'] = {
    ['hide_special_on_workspace_change'] = true,
    ['scroll_event_delay'] = 0,
    ['workspace_back_and_forth'] = true,
  },
  ['cursor'] = {
    ['hotspot_padding'] = 1,
    ['zoom_disable_aa'] = true,
    ['zoom_factor'] = 1,
    ['zoom_rigid'] = false,
  },
  ['decoration'] = {
    ['active_opacity'] = 1.0,
    ['blur'] = {
      ['brightness'] = 1,
      ['contrast'] = 0.89,
      ['enabled'] = true,
      ['input_methods'] = true,
      ['input_methods_ignorealpha'] = 0.8,
      ['new_optimizations'] = true,
      ['noise'] = 0.05,
      ['passes'] = 3,
      ['popups'] = false,
      ['popups_ignorealpha'] = 0.6,
      ['size'] = 10,
      ['special'] = false,
      ['vibrancy'] = 0.5,
      ['vibrancy_darkness'] = 0.5,
      ['xray'] = true,
    },
    ['dim_inactive'] = true,
    ['dim_special'] = 0.2,
    dim_strength = 0.05,
    inactive_opacity = 0.9,
    rounding = 18,
    rounding_power = 2.5,
    shadow = {
      color = 'rgba(00000020)',
      enabled = true,
      offset = { 0, 2 },
      range = 20,
      render_power = 10,
    },
  },
  dwindle = {
    preserve_split = true,
    smart_resizing = false,
    smart_split = false,
  },
  general = {
    allow_tearing = false,
    border_size = 1,
    col = {
      active_border = {
        angle = 45,
        colors = { 'rgba(d3869bee)', 'rgba(d8a657ee)' },
      },
      inactive_border = 'rgba(595959aa)',
    },
    gaps_in = 5,
    gaps_out = 5,
    layout = 'dwindle',
    no_focus_fallback = true,
    resize_on_border = false,
    snap = {
      enabled = true,
      monitor_gap = 5,
      respect_gaps = true,
      window_gap = 4,
    },
  },
  ['input'] = {
    ['follow_mouse'] = 1,
    ['kb_layout'] = 'us',
    ['kb_options'] = 'caps:swapescape',
    ['kb_variant'] = 'colemak_dh',
    ['numlock_by_default'] = true,
    ['off_window_axis_events'] = 2,
    ['repeat_delay'] = 250,
    ['repeat_rate'] = 35,
    ['sensitivity'] = 0,
    ['touchpad'] = {
      ['clickfinger_behavior'] = true,
      ['disable_while_typing'] = true,
      ['natural_scroll'] = true,
      ['scroll_factor'] = 0.7,
    },
  },
  ['misc'] = {
    ['allow_session_lock_restore'] = true,
    ['animate_manual_resizes'] = false,
    ['animate_mouse_windowdragging'] = false,
    ['disable_hyprland_logo'] = true,
    ['disable_splash_rendering'] = true,
    ['enable_swallow'] = false,
    ['focus_on_activate'] = true,
    ['initial_workspace_tracking'] = false,
    ['key_press_enables_dpms'] = true,
    ['mouse_move_enables_dpms'] = true,
    ['on_focus_under_fullscreen'] = 2,
    ['session_lock_xray'] = true,
    ['swallow_regex'] = '(foot|kitty|allacritty|Alacritty)',
  },
  ['scrolling'] = {
    ['column_width'] = 0.9,
    ['direction'] = 'right',
    ['fullscreen_on_one_column'] = true,
  },
})

-- These are set using uwsm's env-hyprland or env
-- settings.env
-- hl.env("XCURSOR_SIZE", "24")
-- hl.env("HYPRCURSOR_SIZE", "24")

-- settings.gesture
hl.gesture({
  ['action'] = 'workspace',
  ['direction'] = 'horizontal',
  ['fingers'] = 4,
})
hl.gesture({ ['action'] = 'move', ['direction'] = 'swipe', ['fingers'] = 3 })
hl.gesture({ ['action'] = 'fullscreen', ['direction'] = 'pinch', ['fingers'] = 3 })

-- settings.monitor
hl.monitor({
  ['mode'] = 'preferred',
  ['output'] = '',
  ['position'] = 'auto',
  ['scale'] = 1,
})

-- settings.permission
hl.permission({
  ['binary'] = '/nix/store/naigfwbkdlnmz4apjnqrgk5mvhl4p886-grim-1.5.0/bin/grim',
  ['mode'] = 'allow',
  ['type'] = 'screencopy',
})
hl.permission({
  ['binary'] = '/nix/store/l50glvp689h6y1flq22b3pinq9ixya47-hyprlock-0\\.9\\.5/bin/hyprlock',
  ['mode'] = 'allow',
  ['type'] = 'screencopy',
})
hl.permission({
  ['binary'] = '/nix/store/8wr7irfps974z88n1xw1bra3cmh81ny1-xdg-desktop-portal-hyprland-1.3.12/libexec/.xdg-desktop-portal-hyprland-wrapped',
  ['mode'] = 'allow',
  ['type'] = 'screencopy',
})

-- settings.window_rule
hl.window_rule({
  ['match'] = { ['class'] = '.*' },
  ['name'] = 'suppress-maximize-events',
  ['suppress_event'] = 'maximize',
})
hl.window_rule({
  ['match'] = {
    ['class'] = '^$',
    ['float'] = true,
    ['fullscreen'] = false,
    ['pin'] = false,
    ['title'] = '^$',
    ['xwayland'] = true,
  },
  ['name'] = 'fix-xwayland-drags',
  ['no_focus'] = true,
})

-- extraConfig
-- Switch workspaces with mod + [0-9]
-- Move active window to a workspace with mod + SHIFT + [0-9]
for i = 1, 10 do
  local key = i % 10 -- 10 maps to key 0
  hl.bind(mod .. ' + ' .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(mod .. ' + SHIFT + ' .. key, hl.dsp.window.move({ workspace = i }))
end

-- Noctalia Shell bindings
local ipc = 'noctalia msg '

-- Core binds
hl.bind(mod .. '+Space', hl.dsp.exec_cmd(ipc .. 'panel-toggle launcher'))
hl.bind(mod .. '+S', hl.dsp.exec_cmd(ipc .. 'panel-toggle control-center'))
hl.bind(mod .. '+comma', hl.dsp.exec_cmd(ipc .. 'settings-toggle'))

-- Media keys
hl.bind('XF86AudioRaiseVolume', hl.dsp.exec_cmd(ipc .. 'volume-up'))
hl.bind('XF86AudioLowerVolume', hl.dsp.exec_cmd(ipc .. 'volume-down'))
hl.bind('XF86AudioMute', hl.dsp.exec_cmd(ipc .. 'volume-mute'))
hl.bind('XF86MonBrightnessUp', hl.dsp.exec_cmd(ipc .. 'brightness-up'))
hl.bind('XF86MonBrightnessDown', hl.dsp.exec_cmd(ipc .. 'brightness-down'))

-- Noctalia Settings
hl.window_rule({
  match = { class = 'dev.noctalia.Noctalia' },
  float = true,
  size = { 1080, 920 },
})

-- Enable blur in noctalia shell
hl.layer_rule({
  name = 'noctalia',
  match = {
    namespace = '^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd)$',
  },
  no_anim = true,
  ignore_alpha = 0.5,
  blur = true,
  blur_popups = true,
})
