async-dns=true
bt-enable-lpd=true
bt-hash-check-seed=true
bt-max-peers=0
bt-request-peer-speed-limit=50K
bt-require-crypto=true
bt-save-metadata=true
bt-seed-unverified=true
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce
bt-tracker-connect-timeout=10
bt-tracker-timeout=10
continue=true
dht-listen-port=60000
dir=/home/krish/Downloads
disable-ipv6=false
disk-cache=128M
enable-dht=true
enable-mmap=true
enable-peer-exchange=true
enable-rpc=true
file-allocation=falloc
follow-torrent=true
force-save=false
ftp-pasv=true
input-file=/home/krish/.config/aria2/session.lock
listen-port=60000
lowest-speed-limit=0
max-concurrent-downloads=5
max-connection-per-server=16
max-download-limit=0
max-overall-download-limit=0
max-overall-upload-limit=0
max-tries=5
max-upload-limit=500K
min-split-size=1M
on-bt-download-complete=notify-send 'aria2' 'Torrent complete'
on-download-complete=notify-send 'aria2' 'Download complete'
on-download-error=notify-send 'aria2' 'Download failed'
on-download-pause=notify-send 'aria2' 'Download paused'
on-download-start=notify-send 'aria2' 'Download started'
peer-id-prefix=-TR2770-
retry-wait=0
rpc-allow-origin-all=true
rpc-listen-all=false
rpc-listen-port=6800
save-session=/home/krish/.config/aria2/session.lock
save-session-interval=30
seed-ratio=0.000000
split=16
user-agent=Transmission/2.77
