{
  flake.nixosModules.niri = {
    programs.niri = {
      enable = true;
      useNautilus = false;
    };
  };

  flake.homeModules.niri =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      # Auto-generated from home-manager options - do NOT edit by hand, it's
      # regenerated on every `home-manager switch`. Edit theme.nix / keymap.nix
      # instead. Lands at cfg/hm_config.kdl, included from config.kdl.
      hmConfigKdl = pkgs.writeText "hm_config.kdl" ''
        // Auto-generated by modules/wm/niri/module.nix from home-manager options.
        // Do not edit by hand.

        environment {
          GTK_THEME "${config.gtk.theme.name}"
          QS_ICON_THEME "${config.gtk.iconTheme.name}"
        }

        cursor {
          xcursor-theme "${config.home.pointerCursor.name}"
          xcursor-size ${toString config.home.pointerCursor.size}
        }

        input {
          keyboard {
            xkb {
              layout "${config.home.keyboard.layout}"
              variant "${config.home.keyboard.variant}"
              options "${lib.concatStringsSep "," config.home.keyboard.options}"
            }
          }
        }
      '';

      # Validate config.kdl together with the whole cfg/ tree (the static split
      # files plus the generated hm_config.kdl), assembled into the same relative
      # layout they'll have on disk ($XDG_CONFIG_HOME/niri/{config.kdl,cfg/*.kdl}).
      # niri validate needs to actually open every included file to succeed, so
      # they all have to be in place, at the right relative paths, before it runs.
      niriConfigChecked =
        pkgs.runCommand "niri-config-checked"
          {
            nativeBuildInputs = [ pkgs.niri ];
          }
          ''
            mkdir -p tmp/cfg
            cp ${./config.kdl} tmp/config.kdl
            cp -r ${./cfg}/. tmp/cfg/
            cp ${hmConfigKdl} tmp/cfg/hm_config.kdl
            niri validate --config tmp/config.kdl

            # Only touch $out once validation has actually passed.
            mkdir -p $out/cfg
            cp tmp/config.kdl $out/config.kdl
            cp -r tmp/cfg/. $out/cfg/
          '';
    in
    {
      xdg.portal = {
        extraPortals = with pkgs; [
          xdg-desktop-portal-gtk
        ];
        configPackages = [ pkgs.niri ];
      };
      xdg.configFile."niri/config.kdl".source = "${niriConfigChecked}/config.kdl";
      xdg.configFile."niri/cfg" = {
        source = "${niriConfigChecked}/cfg";
        recursive = true;
      };
    };
}
